### PR TITLE
Networking unet

### PR DESCRIPTION
**Pull request by zergez**
The project with Unet working.

Im not sure if Im requesting to merge the master branch or if im requesting to create a new branch.
I dont want to create problems merging with the master branch.

### CODE REVIEW

**Comment by BK-TN** [comment]
I had a look at it, tried to start a server and connect a client to it locally. It feels a bit sluggish but works well. Ball syncing was especially very laggy, which might be because I was only testing locally. The only thing that could use a LOT of work is your UI design. The elements you have are neither pretty nor consistent, and some useful things are missing like a player list. However I think with more polish this could be a very decent online implementation.

I will not be accepting the pull request - I would prefer doing it my own way (Check out the `networking_without_unet` branch), even though it requires more work. UNet doesn't support dedicated servers, which multiple people have asked for. Also the 20 CCU limit is pretty annoying and paying for a higher CCU doesn't make sense with how little money the game makes. Biggest reason though is that writing a multiplayer system from scratch is honestly pretty fun and challenging, while using UNet never really worked for me.

All in all, good job bro. Even though I've never been a fan of your mobile port I still wish you the best of luck.

**Comment by zergez** [comment]
Yes, I was expecting that as Unet have lot of restrictions but I decided to star learning multiplayer from Unet because I thought it would be the easiest way..., but I suppose is better work with you own server.
Im working on a new level, I will make a new branch and a pull request when I finish it. Also I will convert the Android version to free in the next Update with the new level im working on.
Btw, the free version of android was deleted by google and rejected tons of time when I tried to reupload it, never was my intention to make only available the pay version.
Thanks for the feedback, and I also wish you the best.


captura de pantalla 2016-08-13 a las 3 41 26 p m

**Comment by BK-TN** [comment]
Woah nice track design, I guess you saw my blog post about it. If you want to share it as you said I will try to spice it up with new gameplay items and maybe obstacles.

Sorry to hear the free version was taken down. What did they reject it for?

**Comment by zergez** [comment]
They never tell exactly why, google just reject apps without any warning but I think it was because the first word of the tittle was similar to Sonic name ("Sanic ball"), but when I wrote the Word "NoAds" before "Sanic Ball" in the tittle they accept it. The problem is that they accept all apps first and then reject them after a while.
With Apple, they review the app, and if saw something dont like they tell you first so you can make the propper changes. 
Gameplay items and obstables sounds pretty cool, I think I can have the level ready by next Saturday.

**Pull request closed without merging**
